DROP TABLE IF EXISTS BOOK;
DROP TABLE IF EXISTS AUTHOR;

CREATE TABLE AUTHOR (
  ID    BIGINT NOT NULL PRIMARY KEY,
  FIRST_NAME      VARCHAR2(50) NOT NULL,
  LAST_NAME       VARCHAR2(50)  NOT NULL
);

CREATE TABLE BOOK (
  ID    BIGINT NOT NULL PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  ISBN  VARCHAR(50) NOT NULL,
  PAGE_COUNT INT NOT NULL,
  AUTHOR_ID BIGINT NOT NULL,
  FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHOR(ID)
);