/*
 * This file is generated by jOOQ.
*/
package com.example.DemoGraphQL;


import com.example.DemoGraphQL.tables.Author;
import com.example.DemoGraphQL.tables.Book;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.AUTHOR</code>.
     */
    public static final Author AUTHOR = com.example.DemoGraphQL.tables.Author.AUTHOR;

    /**
     * The table <code>PUBLIC.BOOK</code>.
     */
    public static final Book BOOK = com.example.DemoGraphQL.tables.Book.BOOK;
}
